format = """${hostname}${git_branch}${git_status}${character}"""


[hostname]
ssh_only = false
format   = "│ [$hostname](fg:#58a6ff) "

[character]
success_symbol = "[❯](fg:white)"
error_symbol   = "[❯](fg:red)"

[git_branch]
format = '(│ [$branch]($style))'

[git_status]
format     = "( $conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind)"
conflicted = "[${count} ](fg:#da3633)"
staged     = "[+${count} ](fg:#58a6ff)"
untracked  = "[U${count} ](fg:#76e3ea)"
modified   = "[M${count} ](fg:#d29922)"
renamed    = "[R${count} ](fg:#d29922)"
deleted    = "[D${count} ](fg:#da3633)"
stashed    = "[S${count} ](fg:#a371f7)"
ahead      = "[A${count} ](fg:#3fb950)"
behind     = "[B${count} ](fg:#804142)"
